### PR TITLE
Add a token  Densaugeo/uploadserver#3

### PR DESCRIPTION
**Pull request by lishoujun**

### CODE REVIEW

**Comment by Densaugeo** [comment]
Thanks for adding this feature, I'll test this on a few recent Python versions when I get the chance. Meanwhile, here are some initial comments:

When an upload is rejected due to a bad token, a 401 response should be returned, and the log message should be formatted the same as the rest of the logs. This could be done by something like this:
~~~
    def do_POST(self):
        if self.path == '/upload':
            if receive_upload(self) == 0: send_upload_page(self)
            else: self.send_error(http.HTTPStatus.UNAUTHORIZED, "Token error")
        else: self.send_error(http.HTTPStatus.NOT_FOUND, "Can only POST to /upload")
~~~
instead of the print statement in receive_upload() (send_error() handles both sending the response code and log formatting).

In `__main__.py`, `parser.add_argument('-t', '-token', ...)` should be changed to `parser.add_argument('--token', '-t', ...)` for consistency with the other arguments. This also means the token can be referred to later as args.token (rather than args.t).

**Comment by lishoujun** [comment]
I am so so happy to receive your comments.
And thank you for so detail  'how to' .    I will fix this bugs quickly.

**Comment by lishoujun** [comment]
Sorry it takes  long time, I am busy this days.   please review again.  @Densaugeo

**Comment by Densaugeo** [comment]
Very close, but when a token is rejected this script will send both a 403 forbidden response and a 200 OK. Each request should get only one response. This can be done by adding an else:

~~~
if http.HTTPStatus.FORBIDDEN == retcode:
    self.send_error(retcode, "Token is enabled on this server, and your token is error")
else: send_upload_page(self)
~~~

**Comment by lishoujun** [comment]
I thought send_error will end the process, so the code after will not be exec.

I will test it  and add an else block

**Comment by lishoujun** [comment]
else is ok but i prefer return to avoid   indent ，may I ?

**Comment by Densaugeo** [comment]
I've tested it on 3.6, 3.7, 3.8, and 3.9, and it looks good! Thanks for adding a feature.

**Pull request merged**
