### PR TITLE
Add streaming upload option

### PR DESCRIPTION
**Pull request by NteRySin**
Hello,

Here is a new way of uploading files allowing for very big files. The difference with the current implementation is that it is being streaming in a destination, instead of storing it in memory.

There is some refactoring also.

The new code requires the packages streaming-form-data and tqdm, can you help me find where to configure it?

Thanks for your work!

### CODE REVIEW

**Comment by Densaugeo** [comment]
I'm avoiding adding any dependencies outside Python's built-in modules, and keeping this module narrow in scope.

If you want to add more complex features that require more dependencies, I'd be open to refactoring this module so that you could create a new module which imports it and adds the new functionality on top.

**Comment by NteRySin** [comment]
Thanks for your answer! Yes, I'd be interested in something like this, I really need to upload big files. What could I do to help?

**Comment by Densaugeo** [comment]
I'll figure out a more extensible architecture tomorrow and outline my ideas here. It'll probably be something like moving most of the functions into __init.py__ (where they can be imported to other modules) and breaking most of the `if __name__ == 'main':` block into importable functions.

You'll need to set up a repo for your new module, and a name on PyPI (if you want to be able to install with pip).

**Comment by NteRySin** [comment]
I removed the dependency to tqdm and simplified the code, could you give it a look at the function receive_upload()?
https://github.com/NteRySin/uploadserver/blob/76448651b8b386745f0c21295df349c4ddca086f/uploadserver/__init__.py#L41

It still requires the https://github.com/siddhantgoel/streaming-form-data dependency (which is continuously maintained), but it has the advantage of requiring the same parameters as your implementation and doesn't rely on the RAM to receive files.

Would you consider having this dependency? Else, I'll extend you impelemention as discussed :)

**Comment by Densaugeo** [comment]
I'd still prefer not to have the dependency. Additionally, it appears to use temporary files for handling uploads, which leads to a lot of possible edge cases around temporary file permissions that I'd rather not deal with.

Here's what I'm thinking the easiest way to extend is: Move everything in `__main__.py` into `__init__.py`, and wrap the main block in a function, Then you could write a script that does something like this:

~~~
import uploadserver

old_receive_upload = uploadserver.receive_upload

def new_receive_upload(handler):
    print('Do new stuff')
    old_receive_upload(handler)

uploadserver.receive_upload = new_receive_upload

if __name__ == '__main__':
    uploadserver.main()
~~~

You wouldn't need to modify the arguments since the new script would be only for streaming uploads.

Before I do the refactor, do you see any obvious issues with this plan?

**Comment by NteRySin** [comment]
I don't see any issue with your plan, it should work.

Please consider https://github.com/Densaugeo/uploadserver/pull/8 before doing the refactoring, it should ease the next implementation.

Many thanks for your consideration!

**Comment by Densaugeo** [comment]
I've completed my refactor. I'll wait to hear if it works for you before tagging the new version and releasing it as 2.0.0. Any breaking changes after that will be a major version increment, so the interface should be stable if you use 2.x as your dependency.

Here's a small example of how I designed it to be extended:
~~~
import uploadserver

old_receive_upload = uploadserver.receive_upload

def new_receive_upload(handler):
    print('Do new stuff')
    return old_receive_upload(handler)

uploadserver.receive_upload = new_receive_upload

if __name__ == '__main__':
    uploadserver.main()
~~~
After you've made your streaming version, I'd encourage you to publish it on PyPI too!

**Comment by NteRySin** [comment]
Wow, very nice work! I've gave it a look and it seems to be fine. I'll have to test it with my own implementation again.

https://github.com/Densaugeo/uploadserver/blob/12229ac1ccaf1f60a4319ffba78bdb7f6c6b8e6f/uploadserver/__init__.py#L238-L268
Would it be possible to extract this in a new function (e.g. start_server()), in order for it to be callable from another Python module directly?

https://github.com/Densaugeo/uploadserver/blob/12229ac1ccaf1f60a4319ffba78bdb7f6c6b8e6f/uploadserver/__init__.py#L255-L268
It would be possible to do something like this (and similar for Python < 3.8) in order to avoid having to maintain the test() methods from http.server, the drawback being that the log messages wouldn't reflect the HTTPS:
```
class DualStackServer(http.server.ThreadingHTTPServer):
    def server_bind(self):
        # suppress exception when protocol is IPv4
        with contextlib.suppress(Exception):
            self.socket.setsockopt(
                socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 0)
            bind = super().server_bind()
            if args.server_certificate:
                self.socket = ssl_wrap(self.socket)
            return bind

http.server.test(
    HandlerClass=handler_class,
    ServerClass=DualStackServer,
    port=args.port,
    bind=args.bind,
)
```

Thanks again! :)

**Comment by Densaugeo** [comment]
Yes, main() can certainly be subdivided. Perhaps split it into a function for parsing args, and another for starting the server. I can do that after work tomorrow.

That's an interesting idea for the SSL wrapper, it would remove a lot of reimplementation. I might look into if there's a way to intercept the print calls from the built-in test() function and substitute them without it being too messy. I'm pretty picky about having the right protocol in the log message though, since I have previously copy/pasted URLs from the terminals and then spent 2 hours troubleshooting an HTTPS connection without realizing the URL had the wrong protocol...

**Pull request closed without merging**
